version: '2'

dockerdoc:
  image: docs/archive:v1.11
  container_name: DockerDoc
  environment:
    - VIRTUAL_HOST=doc.puzle.xyz
    - LETSENCRYPT_HOST=doc.puzle.xyz
    - LETSENCRYPT_EMAIL=contact@puzle.xyz
  ports:
    - 4000:4000
