nextcloud-db:
  image: mariadb:${NEXTCLOUD_MARIADB_VERSION}
  container_name: mariadb-${NEXTCLOUD_SUBDOMAIN}-${DOMAIN}
  volumes:
    - ${DATABASE_STORAGE_ROOT}/${NEXTCLOUD_DB_DATA_DIR}:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DB_NAME}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
nextcloud:
  image: wonderfall/nextcloud:${NEXTCLOUD_VERSION}
  container_name: ${NEXTCLOUD_SUBDOMAIN}-${DOMAIN}
  links:
    - nextcloud-db:nextcloud-db
  environment:
    - UID=1000
    - GID=1000
    - UPLOAD_MAX_SIZE=10G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - REDIS_MAX_MEMORY=64mb
    - CRON_PERIOD=15m
    - TZ=Europe/Berlin
    - ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
    - ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    - DB_TYPE=mysql
    - DB_NAME=${MYSQL_DB_NAME}
    - DB_USER=${MYSQL_USER}
    - DB_PASSWORD=${MYSQL_PASSWORD}
    - DB_HOST=nextcloud-db
    - VIRTUAL_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_HOST=${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_EMAIL=contact@${NEXTCLOUD_SUBDOMAIN}.${DOMAIN}
  volumes:
    - ${VOLUME_STORAGE_ROOT}/${NEXTCLOUD_DATA_DIR}:/data
    - ${VOLUME_STORAGE_ROOT}/${NEXTCLOUD_CONFIG_DIR}:/config
    - ${VOLUME_STORAGE_ROOT}/${NEXTCLOUD_APPS_DIR}:/apps2
  ports:
    - 127.0.0.1:${NEXTCLOUD_WEB_PORT}:8888
