summoner:
  version: 0.2.0
  install_dir: /path/to/install/directory
  minions_dir: /path/to/minions/directory
  domain: example.com
  vsroot: ~/Summoner/data
  dbsroot: ~/Summoner/data/database
  reverse_proxy: nginx
  applications:
    - ghost
    - nextcloud
    - wekan
