mysql:
  restart: always
  image: mysql:${MATTERMOST_MYSQL_VERSION}
  environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  volumes:
    - ${DATABASE_STORAGE_ROOT}/${MATTERMOST_DB_DATA_DIR}:/var/lib/mysql
  container_name: mysql-${MATTERMOST_SUBDOMAIN}-${DOMAIN}

mattermost:
  restart: always
  image: jasl8r/mattermost:${MATTERMOST_VERSION}
  links:
    - mysql:mysql
  ports:
    - 127.0.0.1:${MATTERMOST_WEB_PORT}:80
  environment:
    - MATTERMOST_SECRET_KEY=d9wVPX3x7h9wWkVVcwwTJ4knhfLkr3Mzf4CNL3WgdTTpJvjqWK3VzTp7pHHhjcqs
    - MATTERMOST_LINK_SALT=NPgCWVg4sK4c9dgTjrPtCWjkzMvHFtqzNLvXTJdKt4gWtzLXzzvjJ4Kjqs3fFkRv
    - MATTERMOST_RESET_SALT=7frPRCsdxs3zKLhKKWFkt3ksprzWFTkw3vnhcHXMp3d4zjkKjkPVMXsFxWRzf3qn
    - MATTERMOST_INVITE_SALT=7frPRCsdxs3zKLhKKWFkt3ksprzWFTkw3vnhcHXMp3d4zjkKjkPVMXsFxWRzf3qn
    - VIRTUAL_HOST=${MATTERMOST_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_HOST=${MATTERMOST_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_EMAIL=${MATTERMOST_SUBDOMAIN}.${DOMAIN}
  volumes:
    - ${VOLUME_STORAGE_ROOT}/${MATTERMOST_DATA_DIR}:/opt/mattermost/data
  container_name: ${MATTERMOST_SUBDOMAIN}-${DOMAIN}
