redis:
  restart: always
  image: sameersbn/redis:${GITLAB_REDIS_VERSION}
  container_name: redis-${GITLAB_SUBDOMAIN}-${DOMAIN}
  volumes:
  - ${VOLUME_STORAGE_ROOT}/docker/gitlab/redis:/var/lib/redis

postgresql:
  restart: always
  image: sameersbn/postgresql:${GITLAB_POSTGRESQL_VERSION}
  container_name: postgresql-${GITLAB_SUBDOMAIN}-${DOMAIN}
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - ${VOLUME_STORAGE_ROOT}/docker/gitlab/postgresql:/var/lib/postgresql:Z

registry:
  restart: always
  image: registry:${GITLAB_REGISTRY_VERSION}
  container_name: registry-${GITLAB_SUBDOMAIN}-${DOMAIN}
  volumes:
  - ${VOLUME_STORAGE_ROOT}/docker/gitlab/gitlab/data/shared/registry:/registry
  - ${VOLUME_STORAGE_ROOT}${CERT_DIR}:/certs
  environment:
  - REGISTRY_LOG_LEVEL=info
  - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
  - REGISTRY_AUTH_TOKEN_REALM=https://${GITLAB_SUBDOMAIN}.${DOMAIN}/jwt/auth
  - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
  - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
  - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.crt
  - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.crt
  - REGISTRY_HTTP_TLS_KEY=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.key
  - REGISTRY_STORAGE_DELETE_ENABLED=true
  - VIRTUAL_HOST=registry.${GITLAB_SUBDOMAIN}.${DOMAIN}
  - VIRTUAL_PORT=5000
  - VIRTUAL_PROTO=https
  - LETSENCRYPT_HOST=registry.${GITLAB_SUBDOMAIN}.${DOMAIN}
  - LETSENCRYPT_EMAIL=puzle.project@gmail.com

gitlab:
  restart: always
  image: sameersbn/gitlab:${GITLAB_VERSION}
  container_name: ${GITLAB_SUBDOMAIN}-${DOMAIN}
  links:
    - postgresql
    - redis
  ports:
    - "${GITLAB_SSH_PORT}:22"
    - "5000:5000"
    - "${GITLAB_WEB_PORT}:80"
    - "${GITLAB_HTTPS_PORT}:443"
  volumes:
  - ${VOLUME_STORAGE_ROOT}/docker/gitlab/gitlab:/home/git/data:Z
  - ${VOLUME_STORAGE_ROOT}/docker/gitlab/gitlab/logs:/var/log/gitlab
  - ${VOLUME_STORAGE_ROOT}${CERT_DIR}:/certs
  environment:
  - DEBUG=false

  - DB_ADAPTER=postgresql
  - DB_HOST=postgresql
  - DB_PORT=5432
  - DB_USER=gitlab
  - DB_PASS=password
  - DB_NAME=gitlabhq_production

  - REDIS_HOST=redis
  - REDIS_PORT=6379

  - TZ=Europe/Paris
  - GITLAB_TIMEZONE=Paris

  - GITLAB_HTTPS=true
  - SSL_SELF_SIGNED=false
  - SSL_KEY_PATH=/certs/${GITLAB_SUBDOMAIN}.${DOMAIN}.key
  - SSL_CERTIFICATE_PATH=/certs/${GITLAB_SUBDOMAIN}.${DOMAIN}.crt
  - SSL_DHPARAM_PATH=/certs/${GITLAB_SUBDOMAIN}.${DOMAIN}.dhparam.pem
  - HSTS MAXAGE=0
  - NGINX_HSTS_ENABLED=false

  - GITLAB_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
  - GITLAB_PORT=443
  - GITLAB_SSH_PORT=10022
  - GITLAB_SECRETS_SECRET_KEY_BASE=cdJXTPqnwcmtrqcHqhz7xqHmCkFngMgRgq7wVTspVXMgq7qKvVrn47HnmxTtX4zK
  - GITLAB_SECRETS_DB_KEY_BASE=JPrx3ngpbwmLknsLqRKdMWvwwb9MLvLfkCcCfWpxVbwfJMJcvkHRKgTt9HpfmdgX
  - GITLAB_SECRETS_OTP_KEY_BASE=9hbKtnNLmxCKdxMwTLKdnd4wWzRCTjzMs7dnhpNHLCxdrhwHhj3fPVtJ7KfdFLtf

  - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
  - GITLAB_NOTIFY_PUSHER=false

  - GITLAB_EMAIL=notifications@example.com
  - GITLAB_EMAIL_REPLY_TO=noreply@example.com
  - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

  - GITLAB_BACKUP_SCHEDULE=daily
  - GITLAB_BACKUP_TIME=01:00

  - SMTP_ENABLED=true
  - SMTP_DOMAIN=www.gmail.com
  - SMTP_HOST=smtp.gmail.com
  - SMTP_PORT=587
  - SMTP_USER=puzle.project@gmail.com
  - SMTP_PASS=iK5.z/mlsO4!oik
  - SMTP_STARTTLS=true
  - SMTP_AUTHENTICATION=login

  - IMAP_ENABLED=false
  - IMAP_HOST=imap.gmail.com
  - IMAP_PORT=993
  - IMAP_USER=mailer@example.com
  - IMAP_PASS=password
  - IMAP_SSL=true
  - IMAP_STARTTLS=false

  - VIRTUAL_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
  - VIRTUAL_PORT=${GITLAB_HTTPS_PORT}
  - VIRTUAL_PROTO=https
  - LETSENCRYPT_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
  - LETSENCRYPT_EMAIL=puzle.project@gmail.com

  - GITLAB_REGISTRY_ENABLED=true
  - GITLAB_REGISTRY_HOST=registry.${GITLAB_SUBDOMAIN}.${DOMAIN}
  - GITLAB_REGISTRY_PORT=5500
  - GITLAB_REGISTRY_API_URL=https://registry.${GITLAB_SUBDOMAIN}.${DOMAIN}:5000/
  - GITLAB_REGISTRY_ISSUER=gitlab-issuer
  - GITLAB_REGISTRY_KEY_PATH=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.key
  - SSL_REGISTRY_KEY_PATH=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.key
  - SSL_REGISTRY_CERT_PATH=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.crt
