postgresql:
  restart: always
  image: sameersbn/postgresql:${GITLAB_POSTGRE_VERSION}
  container_name: postgresql-${GITLAB_SUBDOMAIN}-${DOMAIN}
  environment:
    - DB_NAME=gitlabhq_production
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_EXTENSION=pg_trgm
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql

redis:
  restart: always
  image: sameersbn/redis:${GITLAB_REDIS_VERSION}
  container_name: redis-${GITLAB_SUBDOMAIN}-${DOMAIN}
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis

gitlab:
  image: sameersbn/gitlab:${GITLAB_VERSION}
  container_name: ${GITLAB_SUBDOMAIN}-${DOMAIN}
  links:
    - postgresql:postgresql
    - redis:redisio
  ports:
    - "${GITLAB_SSH_PORT}:22"
    - "${GITLAB_WEB_PORT}:80"
    - "${GITLAB_HTTPS_PORT}:443"
  environment:
    - GITLAB_PORT=${GITLAB_WEB_PORT}
    - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
    - GITLAB_SECRETS_SECRET_KEY_BASE=cdJXTPqnwcmtrqcHqhz7xqHmCkFngMgRgq7wVTspVXMgq7qKvVrn47HnmxTtX4zK
    - GITLAB_SECRETS_DB_KEY_BASE=JPrx3ngpbwmLknsLqRKdMWvwwb9MLvLfkCcCfWpxVbwfJMJcvkHRKgTt9HpfmdgX
    - GITLAB_SECRETS_OTP_KEY_BASE=9hbKtnNLmxCKdxMwTLKdnd4wWzRCTjzMs7dnhpNHLCxdrhwHhj3fPVtJ7KfdFLtf
    - VIRTUAL_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_EMAIL=contact@${DOMAIN}
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data

gitlab-runner:
  image: gitlab/gitlab-runner:${GITLAB_CI_VERSION}
  container_name: CI-${GITLAB_SUBDOMAIN}-${DOMAIN}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /srv/gitlab-runner/config:/etc/gitlab-runner
