mysql:
  restart: always
  image: mysql:latest
  environment:
    - MYSQL_USER=mattermost
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=mattermost
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /srv/docker/gitlab/mysql:/var/lib/mysql
  container_name: mysql-${MATTERMOST_SUBDOMAIN}-${DOMAIN}

mattermost:
  restart: always
  image: jasl8r/mattermost:${MATTERMOST_VERSION}
  links:
    - mysql:mysql
  ports:
    - "${MATTERMOST_WEB_PORT}:80"
  environment:
    - MATTERMOST_SECRET_KEY=d9wVPX3x7h9wWkVVcwwTJ4knhfLkr3Mzf4CNL3WgdTTpJvjqWK3VzTp7pHHhjcqs
    - MATTERMOST_LINK_SALT=NPgCWVg4sK4c9dgTjrPtCWjkzMvHFtqzNLvXTJdKt4gWtzLXzzvjJ4Kjqs3fFkRv
    - MATTERMOST_RESET_SALT=7frPRCsdxs3zKLhKKWFkt3ksprzWFTkw3vnhcHXMp3d4zjkKjkPVMXsFxWRzf3qn
    - MATTERMOST_INVITE_SALT=7frPRCsdxs3zKLhKKWFkt3ksprzWFTkw3vnhcHXMp3d4zjkKjkPVMXsFxWRzf3qn
    - VIRTUAL_HOST=${MATTERMOST_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_HOST=${MATTERMOST_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_EMAIL=${MATTERMOST_SUBDOMAIN}.${DOMAIN}
  volumes:
    - /srv/docker/mattermost:/opt/mattermost/data
  container_name: ${MATTERMOST_SUBDOMAIN}-${DOMAIN}
