taigadb:
  image: postgres
  container_name: postgresql-${TAIGA_SUBDOMAIN}-${DOMAIN}
  environment:
    POSTGRES_USER: taiga
    POSTGRES_PASSWORD: Un1c0rn
  volumes:
    - ${VOLUME_STORAGE_ROOT}/${TAIGA_DB_DATA_DIR}:/var/lib/postgresql/data

taigaback:
  image: beevelop/taiga-back:${TAIGA_BACK_VERSION}
  container_name: taigaback-${TAIGA_SUBDOMAIN}-${DOMAIN}
  environment:
    SECRET_KEY: Un1c0rns_4r3_4w3s0m3

    API_SCHEME: http
    FRONT_SCHEME: http

    PUBLIC_REGISTER_ENABLED: "True"
    FEEDBACK_ENABLED: "True"
    FEEDBACK_EMAIL: noreply@${TAIGA_SUBDOMAIN}.${DOMAIN}.com
    STATS_ENABLED: "True"

    FRONT_SITEMAP_ENABLED: "True"

    DEBUG_ENTRYPOINT: "True"
    DEBUG: "True"
    TEMPLATE_DEBUG: "True"

    EMAIL_USE_TLS: "True"
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: unicorn@gmail.com
    EMAIL_HOST_PASSWORD: yourpassword
    DEFAULT_FROM_EMAIL: noreply@${TAIGA_SUBDOMAIN}.${DOMAIN}.com
  links:
    - taigadb:postgres
  volumes:
    - ${VOLUME_STORAGE_ROOT}/${TAIGA_MEDIA_DATA_DIR}:/usr/local/taiga/media
    - ${VOLUME_STORAGE_ROOT}/${TAIGA_STATIC_DATA_DIR}:/usr/local/taiga/static
    - ${VOLUME_STORAGE_ROOT}/${TAIGA_LOGS_DIR}:/usr/local/taiga/logs

taigafront:
  image: beevelop/taiga-front:${TAIGA_FRONT_VERSION}
  container_name: taigafront-${TAIGA_SUBDOMAIN}-${DOMAIN}
  environment:
    TAIGA_DOMAIN: ${DOMAIN}
    TAIGA_SUBDOMAIN: ${TAIGA_SUBDOMAIN}
    SCHEME: http
    DEFAULT_LANGUAGE: en
    PRIVACY_POLICY_URL: https://taiga.example.com/privacy_policy
    TERMS_OF_SERVICE_URL: https://taiga.example.com/tos
    DEBUG_ENTRYPOINT: "True"
    DEBUG: "False"
    VIRTUAL_HOST: "${TAIGA_SUBDOMAIN}.${DOMAIN}"
    LETSENCRYPT_HOST: "${TAIGA_SUBDOMAIN}.${DOMAIN}"
    LETSENCRYPT_EMAIL: "taiga@gmail.com"
  links:
    - taigaback
  volumes_from:
    - taigaback
  ports:
    - ${TAIGA_WEB_PORT}:80
    - ${TAIGA_HTTPS_PORT}:443
