registry:
  restart: always
  image: registry:${REGISTRY_VERSION}
  container_name: registry-${DOMAIN}
  volumes:
    - ${VOLUME_STORAGE_ROOT}/${REGISTRY_DATA}:/var/lib/registry
    - ${VOLUME_STORAGE_ROOT}/${CERT_DIR}:/certs
  environment:
    - REGISTRY_LOG_LEVEL=info
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/${DOMAIN}.crt
    - REGISTRY_HTTP_TLS_KEY=/certs/${DOMAIN}.key
    - REGISTRY_STORAGE_DELETE_ENABLED=true
    - VIRTUAL_HOST=${DOMAIN}
    - VIRTUAL_PORT=5000
    - VIRTUAL_PROTO=https
    - LETSENCRYPT_HOST=${DOMAIN}
    - LETSENCRYPT_EMAIL=registry@${DOMAIN}
  ports:
    - ${REGISTRY_WEB_PORT}:5000
