postgresql:
  restart: always
  image: sameersbn/postgresql:${GITLAB_POSTGRESQL_VERSION}
  container_name: postgresql-${GITLAB_SUBDOMAIN}-${DOMAIN}
  environment:
    - DB_NAME=gitlabhq_production
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_EXTENSION=pg_trgm
  volumes:
    - ${VOLUME_STORAGE_ROOT}/docker/gitlab/postgresql:/var/lib/postgresql

redis:
  restart: always
  image: sameersbn/redis:${GITLAB_REDIS_VERSION}
  container_name: redis-${GITLAB_SUBDOMAIN}-${DOMAIN}
  volumes:
    - ${VOLUME_STORAGE_ROOT}/docker/gitlab/redis:/var/lib/redis

gitlab:
  image: sameersbn/gitlab:${GITLAB_VERSION}
  container_name: ${GITLAB_SUBDOMAIN}-${DOMAIN}
  links:
    - postgresql:postgresql
    - redis:redisio
  ports:
    - "${GITLAB_SSH_PORT}:22"
    - "${GITLAB_WEB_PORT}:80"
    - "${GITLAB_HTTPS_PORT}:443"
  environment:
    - GITLAB_PORT=${GITLAB_WEB_PORT}
    - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
    - GITLAB_SECRETS_SECRET_KEY_BASE=cdJXTPqnwcmtrqcHqhz7xqHmCkFngMgRgq7wVTspVXMgq7qKvVrn47HnmxTtX4zK
    - GITLAB_SECRETS_DB_KEY_BASE=JPrx3ngpbwmLknsLqRKdMWvwwb9MLvLfkCcCfWpxVbwfJMJcvkHRKgTt9HpfmdgX
    - GITLAB_SECRETS_OTP_KEY_BASE=9hbKtnNLmxCKdxMwTLKdnd4wWzRCTjzMs7dnhpNHLCxdrhwHhj3fPVtJ7KfdFLtf
    - GITLAB_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
    - VIRTUAL_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_HOST=${GITLAB_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_EMAIL=contact@${DOMAIN}
    - GITLAB_REGISTRY_ENABLED=true

  volumes:
    - ${VOLUME_STORAGE_ROOT}/docker/gitlab:/home/git/data
    - ${VOLUME_STORAGE_ROOT}${CERT_DIR}:/certs

gitlab-runner:
  image: gitlab/gitlab-runner:${GITLAB_CI_VERSION}
  container_name: CI-${GITLAB_SUBDOMAIN}-${DOMAIN}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${VOLUME_STORAGE_ROOT}/docker/gitlab-runner/config:/etc/gitlab-runner

registry:
  restart: always
  image: registry:2.4.1
  volumes:
  - ${VOLUME_STORAGE_ROOT}/docker/gitlab/gitlab/data/shared/registry:/registry
  - ${VOLUME_STORAGE_ROOT}${CERT_DIR}:/certs
  environment:
  - REGISTRY_LOG_LEVEL=info
  - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
  - REGISTRY_AUTH_TOKEN_REALM=https://${GITLAB_SUBDOMAIN}.${DOMAIN}/jwt/auth
  - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
  - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
  - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.crt
  - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.crt
  - REGISTRY_HTTP_TLS_KEY=/certs/registry.${GITLAB_SUBDOMAIN}.${DOMAIN}.key
  - REGISTRY_STORAGE_DELETE_ENABLED=true

  - VIRTUAL_HOST=registry.${GITLAB_SUBDOMAIN}.${DOMAIN}
  - VIRTUAL_PORT=5000
  - VIRTUAL_PROTO=https
  - LETSENCRYPT_HOST=registry.${GITLAB_SUBDOMAIN}.${DOMAIN}
  - LETSENCRYPT_EMAIL=puzle.project@gmail.com
