version: '3'

services:
  traefik:
    build: .
    # command: --logLevel=DEBUG
    container_name: traefik-${domain}
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    cap_drop:
      - all
    cap_add:
      - net_bind_service
    networks:
      - master

networks:
    master:
        external: true