services:
  wordpress:
    image: wordpress:${WP_VERSION}
    container_name: wordpress-${WP_SUBDOMAIN}-${DOMAIN}
    ports:
      - ${WP_WEB_PORT}:80
    environment:
      - VIRTUAL_HOST=${WP_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_HOST=${WP_SUBDOMAIN}.${DOMAIN}
      - LETSENCRYPT_EMAIL=contact@${DOMAIN}
    environment:
      - WORDPRESS_DB_PASSWORD=example

  mysql:
    image: mariadb
    container_name: mariadb-${WP_SUBDOMAIN}-${DOMAIN}
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=wordpress_${WP_SUBDOMAIN}_${DOMAIN}
      - MYSQL_USER=wordpress_${WP_SUBDOMAIN}_${DOMAIN}
      - MYSQL_PASSWORD=example
