mysql:
  restart: always
  image: mysql:latest
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=wordpress
    - MYSQL_DATABASE=wordpress
    - MYSQL_ROOT_PASSWORD=wordpress
  volumes:
    - ${VOLUME_STORAGE_ROOT}/docker/${WP_SUBDOMAIN}/mysql:/var/lib/mysql
  container_name: mysql-${WP_SUBDOMAIN}-${DOMAIN}

wordpress:
  image: wordpress:${WP_VERSION}
  container_name: wordpress-${WP_SUBDOMAIN}-${DOMAIN}
  links:
    - mysql:mysql
  ports:
    - ${WP_WEB_PORT}:80
  environment:
    - VIRTUAL_HOST=${WP_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_HOST=${WP_SUBDOMAIN}.${DOMAIN}
    - LETSENCRYPT_EMAIL=contact@${DOMAIN}
    - WORDPRESS_DB_USER=wordpress
